### ISSUE TITLE
Subgraph Health checker is not working

### ISSUE THREAD

**Issue by ghost** [FunctionX/fx-subgraph#4]
Hi @zakir-code,

The below subgraph for monitoring the health is not working - 
https://graph-node.functionx.io/index-node/graphql

Thanks,

issei

**Comment by zakir-web3** [comment]
please use `https://graph-node-index.functionx.io/graphql`

**Comment by ghost** [comment]
> please use `https://graph-node-index.functionx.io/graphql`

Thanks zakir! Much appreciated. 👍
